apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-login
spec:
  selector:
    matchLabels:
      app: flask-login
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-login
    spec:
      containers:
        - name: flask-login
          image: docker.io/patelarpitt/assignment1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000