apiVersion: v1
kind: Service
metadata:
  name: flask-login-service
spec:
  selector:
    app: flask-login
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: LoadBalancer
  